name: Lint
on: push
jobs:
    lint:
        runs-on: ubuntu-latest
        name: ESLint
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install Dependencies
              run: npm ci

            - name: ESLint
              run: npm run lint
